authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login),
    path('logout', authapp.logout)
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name="index"),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('contact/', mainapp.contact, name="contact"),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)  # по этому урлу нужно искать фаулы в settings.MEDIA_ROOT, для локальной разработки

mainapp/urls.py
from django.urls import path

from mainapp import views as mainapp

app_name = 'products'

urlpatterns = [
    path('', mainapp.products, name="products"),
    path('<int:pk>/', mainapp.products, name="category")
]

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users', blank=True)
    age = models.PositiveSmallIntegerField(default=18, verbose_name='Возраст')

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Назвине')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name='Название')
    image = models.ImageField(upload_to='product/', blank=True)
    short_desc = models.CharField(max_length=255, blank=True)
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена', default=0)
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

authapp/views.py
# Create your views here.

mainapp/views.py
import json

from django.conf import settings
from django.shortcuts import render

# request - all information about what happened on the user's side
from mainapp.models import Product, ProductCategory


def index(request):
    products_list = Product.objects.all()[:4]
    print(products_list.query)

    context = {
        'title': 'Если у вас возникли вопросы, свяжитесь с нами',
        'products': products_list
    }

    return render(request, 'mainapp/index.html', context)


def contact(request):
    with open(f'{settings.BASE_DIR}/json/contact.json') as contacts_file:
        context = {
            'contacts': json.load(contacts_file)
        }
    return render(request, "mainapp/contact.html", context)


def products(request, pk=None):
    links_menu = ProductCategory.objects.all()
    context = {
        'links_menu': links_menu,
        'title': 'Товары'
    }
    return render(request, "mainapp/products.html", context)

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ title|default:"Магазин"|title }}</title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
</head>
<body>
<div class="container">
    {% block content %}

    {% endblock %}
    <div class="clr"></div>

</div>

{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">{% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% block content %}
    <div class="hero">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
        <h1>наши контакты</h1>
    </div>

    <div class="location">
        {% for item in contacts %}
            <div class="location-1">
                <i class="fa fa-map-marker fa-5x"></i>
                <h4>{{ item.city }}</h4>
                <div class="contacts">
                    <h5>Телефон</h5>
                    <p>{{ item.phone }}</p>
                </div>
                <div class="contacts">
                    <h5>Email</h5>
                    <p>{{ item.email }}</p>
                </div>
                <div class="contacts">
                    <h5>Адрес</h5>
                    <p>{{ item.address }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    <li><a href="{% url 'index' %}"
           class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">домой</a></li>
    <li><a href="{% url 'products:products' %}"
           class="{% if request.resolver_match.namespace == 'products' %}active{% endif %}">продукты</a></li>
    <li><a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">контакты</a>
    </li>
</ul>
<a href="#" class="search"></a>
<a href="#" class="basket"></a>

mainapp/templates/mainapp/includes/inc_products_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'products:products' %}"
               class="{% if request.resolver_match.url_name == 'products' %}active{% endif %}">Все</a></li>
        {% for item in links_menu %}
            <li><a href="{% url 'products:category' item.pk %}"
                   class="{% if request.resolver_match.kwargs.pk == item.pk %}active{% endif %}">{{ item.name }}</a>
            </li>
        {% endfor %}
    </ul>
</div>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="slider">
            <div class="header clearfix">
                {% include 'mainapp/includes/inc_main_menu.html' %}
            </div>
            <div class="text-slider">
                <h3 class="green">тенденции</h3>
                <h3 class="big"> удобные стулья</h3>
                <p>Новый уровень комфорта. Отличные характеристики.</p>
                <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
            </div>
            <div class="navi">
                <a href="#"></a><a href="#"></a><a href="#"></a>
            </div>
        </div>
    </div>
    {{ title }}
    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in products %}
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-1.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.short_desc }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc_products_menu.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{% static 'img/slider1.jpg' %}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">Отличный стул</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> 2585.9 <span>руб</span></p>
                <a href="#" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>Расположитесь комфортно.</p>
                    <p>Отличное качество материалов
                        позволит вам это.</p>
                    <p>Различные цвета</p>
                    <p>высочайший уровень
                        эргономики и прочность.</p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %} alt=""></a>
            </div>
            <div class="related-products clearfix">
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>

            </div>
        </div>
    </div>
{% endblock %}